name: kotlin_web_strings
description: "A Flutter plugin that provides string manipulation functions for Android and Web."
version: 0.0.1
homepage: https://github.com/A-Eric-J/Kotlin_Web_Strings

environment:
  sdk: '>=3.4.4 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  # No need for the `web` package, it's typically not needed in Flutter plugins
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

# The following section is specific to Flutter packages.
flutter:
  plugin:
    platforms:
      android:
        package: com.amiirrallii.kotlin_web_strings
        pluginClass: KotlinWebStringsPlugin
      web:
        pluginClass: StringFunctionsWeb
        fileName: string_functions_web.dart

  # To add assets to your plugin package, uncomment and list the assets here:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # To add custom fonts to your plugin package, uncomment and list the fonts here:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
